### PR TITLE
Pass down references in create_new() and *_join()

### PR DESCRIPTION
**Pull request by agvandervelde**
In order to make the following work (and I suspect a few other subtle reference- and gc-related issues) I propose we pass down references in `create_new()` like we do for connection. This way objects aren't disposed of prematurely. Specifically, I'm running into temporary arrays disappearing when chaining calls like this:

```R
  arr_feature <- query_entity_by_attrs(.rfEnv$meta$arrFeature, list(...), conn=conn)
  q <- arr_feature$semi_join(data.frame(gene_symbol_id = gene_symbol_df$gene_symbol_id))
  q <- q$semi_join(data.frame(organism_id = organism_df$organism_id))
  q <- q$semi_join(data.frame(feature_family_id = feat_fam_df$feature_family_id))
  q <- q$inner_join(arr_gene_symbol,
    by.x = "gene_symbol_id", by.y = "gene_symbol_id",
    join_mode = "cross_join"
  )
...
...
  -- do other things --
...
...
  df <- q$to_df()
```

### CODE REVIEW

**Comment by agvandervelde** [comment]
This turns out to be more complicated. Will follow up on this later.

**Comment by ksens** [comment]
@agvandervelde 

I think @mcolosimo-p4 , @smoore-p4 and others reported similar issues (with lost temporary arrays) previously. Unless I am mixing up issues, the workaround then was to use different object names on the LHS of the assignment rather than recycling the same `q` object i.e. the following would work OK:

```R
  q1 <- arr_feature$semi_join(data.frame(gene_symbol_id = gene_symbol_df$gene_symbol_id))
  q2 <- q1$semi_join(data.frame(organism_id = organism_df$organism_id))
  q3 <- q2$semi_join(data.frame(feature_family_id = feat_fam_df$feature_family_id))
...
```

**Comment by smoore-p4** [comment]
Yeah, at the moment, the suggested thing to do is keep track of the temp arrays in the application code. There is a reason for not just storing the reference by passing it along to the new ones. (There was some worry about circular references, and other issues...) We're thinking about incorporating this into some new functionality such as 'borrowing' the method of handling transactions, and allowing the connection object to hold onto the references... Unfortunately it isn't a simple fix at this point, and we need to dive a little deeper on thinking through the implications.

**Comment by smoore-p4** [comment]
(Follow up for @ksens 's comment. The way I've done it is to use something like:
```
arrop <- temp1 <- arrop$semi_join(....)
arrop <- temp2 <- arrop$semi_join(...)
```

That way temp1 and temp2 are basically holding onto the temp arrays, and the code is a little easier to modify if you need to throw something in between them.

**Pull request closed without merging**
